### ISSUE TITLE
	TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#120] opened 2017-07-09 11:33 UTC
I am getting this error when my Trezor is connected when starting Electrum and when I try to perform a payment from Electrum.

All Fedora packages, trezor-python have protobuffer messages rebuilt with libprotoc 2.6.1
Electrum: 2.8.3
trezor-python: 0.7.16
protobuf-python: 2.6.1
Python 2.7.13

Stacktrace:
```
"sni-qt/11398" WARN  12:51:51.237 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/plugin.py", line 141, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 397, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 427, in force_pair_xpub
    client_xpub = client.get_xpub(derivation)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 153, in get_xpub
    node = self.get_public_node(address_n, creating).node
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 198, in get_public_node
    return super(TrezorClientBase, self).get_public_node(address_n)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 521, in get_public_node
    return self.call(proto.GetPublicKey(address_n=n, ecdsa_curve_name=ecdsa_curve_name, show_display=show_display, coin_name=coin_name))
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 344, in init
    setattr(self, field_name, field_value)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 155, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

```

**Comment by saleemrashid** [comment] 2017-07-09 12:20
@hegjon The issue is that the check in https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L487-L489 was added after libprotoc 2.6.1.

Therefore, when we use `None` in constructors (in this case, `coin_name`), it stores `None` as the `field_value` and runs the `TypeChecker` on it

**Comment by saleemrashid** [comment] 2017-07-09 12:21
@hegjon The issue is that the check in https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L487-L489 was added after libprotoc 2.6.1.

Therefore, when we use `None` in constructors (in this case, `coin_name`), it stores `None` as the `field_value` and runs the `TypeChecker` on it

**Comment by hegjon** [comment] 2017-07-09 15:37
Thanks for your feedback, I will test your patch

**Comment by prusnak** [comment] 2017-07-10 12:29
Closing in favor of https://github.com/trezor/python-trezor/pull/121

**Closed by prusnak** 2017-07-10 12:29 UTC
