### ISSUE TITLE
Unvalidable signed transactions

### ISSUE THREAD

**Issue by idimon4uk** [trezor/python-trezor#240] opened 2018-03-22 17:09 UTC
Hello,
We are interested to use trezor-python , but we have some problems with signature transaction in output. We used Zcash Testnet and Testnet (Bitcoin) and have unvalidable signed transactions. Also we used Trezor T emulator (trezor-core).
 
Can you help us, solve this problem?
 
Input params in the attach pictures.

![image](https://user-images.githubusercontent.com/16037887/37786096-add32fda-2df3-11e8-9357-e27992b971bf.png)
![image](https://user-images.githubusercontent.com/16037887/37786108-b9773840-2df3-11e8-8427-796326fdda2b.png)

**Comment by matejcik** [comment] 2018-03-23 10:18
hello,
it would be great if you could post the screenshot content as text
copy-pasting from pictures is not easy ;)

also, did the same thing happen with BTC testnet?

**Comment by matejcik** [comment] 2018-03-23 11:06
![](https://github.trello.services/images/mini-trello-icon.png) [bad signatures on zcash testnet](https://trello.com/c/F2KCKfQc/4-bad-signatures-on-zcash-testnet)

**Comment by matejcik** [comment] 2018-04-03 16:35
hi, I could not reproduce the problem.
Is this happening to you consistently?
I've been trying to test with Zcash testnet and the site at https://explorer.testnet.z.cash/ has been broken for the last two weeks. Is it possible that your unvalidable transaction is actually a problem with that site, as opposed to a problem with python-trezor?

**Comment by prusnak** [comment] 2018-04-03 16:42
Zcash Testnet was restarted several times. Unit tests fail, because the tests do not match the real values in the current Zcash Testnet blockchain.

**Comment by purpleeggplant** [comment] 2018-05-11 12:04
I get the same issue when signing with Ethereum Offline with trezorctl.

**Comment by matejcik** [comment] 2018-05-11 12:08
@purpleeggplant Ethereum has completely separate code paths, so the underlying issue is going to be different than this one. Care to open a new issue and provide more details? Thanks.

**Comment by prusnak** [comment] 2018-05-11 12:11
I suggest to close this issue, because it's not clear whether it's about Zcash or Bitcoin testnet, and the OP hasn't responded for 2 months. OP: feel free to reopen.

**Comment by purpleeggplant** [comment] 2018-05-11 12:12
For Ethereum this looks like it is being addressed in https://github.com/trezor/python-trezor/issues/236 and will be fixed in 0.9.2 .  Wasn't sure whether this was duplicate or not. @matejcik

**Closed by prusnak** 2018-05-11 12:11 UTC
Labels: needinfo
