### ISSUE TITLE
Replace hidapi dependency with libusb1

### ISSUE THREAD

**Issue by prusnak** [trezor/python-trezor#105] opened 2017-03-06 11:56 UTC
hidapi development has stalled and we don't really need HID features.

The following example script works:

```python
#!/usr/bin/python

import usb1

VENDOR_ID=0x534c
PRODUCT_ID=0x0001
IFACE=0

with usb1.USBContext() as context:

    device = None
    for d in context.getDeviceIterator(skip_on_error=True):
        if d.getVendorID() == VENDOR_ID and d.getProductID() == PRODUCT_ID:
            device = d
            break

    if device is None:
        raise Exception('Device not found')
    print(device)

    handle = device.open()
    if handle is None:
        raise Exception('Cannot open device')
    print(handle)

    if handle.kernelDriverActive(IFACE):
        handle.detachKernelDriver(IFACE)

    handle.claimInterface(IFACE)

    written = handle.interruptWrite(0x01, b'?##' + b'\x00' * 61)
    print(written)

    read = handle.interruptRead(0x81, 64)
    print(read)

    handle.releaseInterface(IFACE)
    handle.close()
```

**Comment by mcudev** [comment] 2017-12-14 12:54
@prusnak I was researching possible application level USB libraries to use to interface with TREZOR v1 devices, and had some questions that coincide with what this issue is advocating.

Since the device registers its interfaces as USB HID with the host system, I'm leaning towards using a hidapi based library by default.

I also found these links that seem to indicate that a hidapi based library may be more compatible with OS X hosts (I don't have one to test):
https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices
https://github.com/gary-rowe/hid4java#why-not-just-use-usb4java-

I'm wondering if you have any experience with library compatibility, or suggestions to avoid pitfalls? Does the fact that "we don't really need HID features" cancel out the compatibility problems?

Also, it looks like now you're in control of pypi for hidapi, so is this issue still as relevant as it was when you opened it?

I'm debating whether to use Python or Java and have narrowed it down to these options that I'm considering:

For Python:
libusb 1.0 based -> https://pypi.python.org/pypi/libusb1/1.6.4
hidapi based     -> https://pypi.python.org/pypi/hidapi/0.7.99.post21

For Java:
libusb 1.0 based -> https://github.com/usb4java/usb4java
hidapi based     -> https://github.com/gary-rowe/hid4java

**Comment by prusnak** [comment] 2017-12-14 16:04
We'll be switching to WebUSB soon (both for T1 and T2). Further research shows it makes sense to support both (libhidapi for legacy HID and libusb for WebUSB).

Funnily enough, the current implementation for Android (trezor-android) works for both HID and WebUSB.

**Comment by mcudev** [comment] 2017-12-15 01:17
Hmm, WebUSB is not very good right now compatibility wise for our purposes.
For example, I'm testing it on Ubuntu 16.04.3 LTS with Chrome 63 and am hitting this issue that the Chrome team has marked as "won't fix": https://bugs.chromium.org/p/chromium/issues/detail?id=679314

To reproduce, plug in T1 device and go to WebUSB test page.
You'll get "DOMException: Unable to claim interface."

Then I run a usb1 python script that contains the following:
```
    if handle.kernelDriverActive(TREZOR_INTERFACE):
      handle.detachKernelDriver(TREZOR_INTERFACE)
```

Then I go back to the WebUSB test page and it works.

**Comment by karel-3d** [comment] 2017-12-15 10:42
It should be enough to install the udev rules that we offer with extension - deb package https://wallet.trezor.io/data/udev/trezor-udev_1_all.deb or manually http://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html

**Comment by prusnak** [comment] 2017-12-15 12:54
@mcudev the WIP branch in this PR: https://github.com/trezor/trezor-mcu/pull/260 is supposed to be used with WebUSB. Currently we ship devices with HID for communication and HID for U2F, after the change we will ship devices with WebUSB for communication and HID for U2F.

**Comment by karel-3d** [comment] 2017-12-15 12:55
@mcudev oh, you are trying webusb with the current firmware with HID interface? OK, this will not work without detaching the driver.

We are making a new firmware that will not have HID (see the branch) and that should not require the python script.

**Comment by mcudev** [comment] 2017-12-15 13:09
neat. thanks, i'll check that out. that should beat running a script from a udev rule :)

**Comment by karel-3d** [comment] 2017-12-15 14:07
@mcudev the problem is that we could not make this backwards compatible. We originally wanted to make the third interface WebUSB and keep the HID interfaces as-are, *but* there is an issue on windows libusb implementation, that is used in Chrome, where HID and WinUSB (which is needed for WebUSB to work without drivers) are on the same device. WinUSB needs to come before HID. 

The resolution is either to wait for Chrome to fix their stuff (they are completely rewriting the usb backend away from libusb), or to put WinUSB/WebUSB first. Which will break things like python-trezor.anyway (if we kept HID but put it on interface 3). And if we put WebUSB first and swith HID to 3, we need to rewrite python-trezor anyway.

We decided to ax HID interface and keep only the webusb one, because the implementation will be cleaner.

**Comment by mcudev** [comment] 2017-12-15 16:58
Yeah, that's a tough spot to be in. No great option so far. I was thinking of fingerprinting the host during enumeration to determine which order of interface descriptors to send, but that may be too brittle.

Hopefully the package maintainers for python-trezor will update in a timely manner when this is ready (e.g.- the debian package [and downstream systems] has only been updated once in the last year+).

**Comment by matejcik** [comment] 2018-03-07 14:54
in the meantime I'm going to try to switch to `hidapi-cffi` so that we can get rid of Cython

**Comment by matejcik** [comment] 2018-06-08 15:58
using hidapi-cffi is not viable because of Windows - we'd need to supply a separate dll. That's the advantage of Cython-based hidapi.

hidapi feature is now marked as extra in python-trezor, so the dependencies don't install by default. That is in anticipation of T1 switch to WebUSB. I'd consider the bug closed through this -- a full switch is not going to happen, AFAICT, we will need to support hidapi as a legacy option in any case.

**Closed by matejcik** 2018-06-08 15:58 UTC
